Feature/drag&drop
NazarenoCarlesso/medilab-manager pull request #110
Opened 2023-03-17 05:58 UTC by Jessicopata

Drag and Drop funcionando

2023-03-17 19:30 UTC, fabianbm15 approved these changes

2023-03-17 21:35 UTC, NazarenoCarlesso requested changes
![Screenshot (142)](https://user-images.githubusercontent.com/95937325/226057500-399df2ae-389e-47ba-b90e-1e980e4d7451.png)
- Hay errores en los tags y falla el deploy
- El react strict debe mantenerse

2023-03-19 00:03 UTC, jeliasincio approved these changes

2023-03-19 00:07 UTC, jeliasincio approved these changes

2023-03-19 11:26 UTC, NazarenoCarlesso approved these changes
Buenisimo

2023-03-20 14:27 UTC, merged