Login component and redux
NazarenoCarlesso/medilab-manager pull request #16
Opened 2023-03-01 21:45 UTC by fabianbm15

Se realiza el componente SignUp, dentro de este componente se encuentra la posibilidad de registrarse o iniciar sesión, se corrigen los validates para que se muestren solo cuando se interactúa con ellos.

Registrarse: se agrega el usuario a la base de datos (tabla patients).
Login: obtiene el token del patient.

2023-03-01 21:50 UTC, juanpablogm12 requested changes
pendiente validación campos vacíos del registro.

2023-03-01 22:41 UTC, juanpablogm12 approved these changes
ok corrección de crear usuario con espacio vacíos.

2023-03-02 01:57 UTC, NazarenoCarlesso commented on client/src/reducer.js
> +      axios.post(`${BACK}/patients/signup`, action.payload);
Los llamados al back no deberian estar en el reducer
Solo los cambios en el store del reducer deben manejarse en las funciones del reducer
Mandar por payload directamente los datos del usuario requeridos

2023-03-02 01:58 UTC, NazarenoCarlesso approved these changes
Buenisimo, se mergea a development para seguir progresando 🚀

2023-03-02 04:28 UTC, IvanAlfredoQQ approved these changes
Cuidado con los states y el manejo del checkbox, yo investigué e implementé una lógica para algo que quería desarrollar en mi PI, y se hace un poco dificil con este método, en el caso de seleccionar un sexo, si uno se marca el otro no puede ser marcado o si está marcado debería desmarcarse, también si marqué ambos por error, cuando desmarco el que no era correcto debería quedar la otra opción marcada (Que se vea en el UI, y el estado no genere error)
Por qué? no queda del todo controlado el formulario y no es entendible para la persona que está usándolo 
![firstCase](https://user-images.githubusercontent.com/114457201/222331282-4365c598-9bbc-4197-b25f-0b33d60cf546.PNG)
![secondCase](https://user-images.githubusercontent.com/114457201/222331289-69080a41-6148-4f16-8b16-029346f63ff9.PNG)

2023-03-02 12:29 UTC, fabianbm15 commented on client/src/reducer.js
> +      axios.post(`${BACK}/patients/signup`, action.payload);
Corregido, se quita la petición al back en el reducer.

2023-03-02 12:34 UTC, merged