se implementa funcionalidad de mercadopago en el front
NazarenoCarlesso/medilab-manager pull request #96
Opened 2023-03-14 15:52 UTC by juanpablogm12

2023-03-14 16:41 UTC, sdelp66 requested changes
esperamos a q este lo de vaciar carrito y ir a detalle de compra.
OTRA: tenemos que tomar los datos para ponerlos en el payment de las tablas no esta (o estaba la ruta xfa revisar)

2023-03-16 05:15 UTC, juanpablogm12 commented
se implementan dos rutas para el resultado del pago en mercadopago
en caso de que sea aprobado al darle clic en el botón crea la orden envía al cart y abre la ventana modal
en caso de que sea rechazado o fallo el pago lo notifica y redirige al cart pero no lo vacía

deshabilite el jwt para poder envíar la orden, mañana reviso con fabian como implementarlo ya que también falta la implementación en la ruta de mercadopago

2023-03-16 11:12 UTC, sdelp66 commented
@juanpablogm12 no pude ver/probar como funciona, avisa cuando podes conectarte y revisamos juntos.. gracias!!

2023-03-17 17:25 UTC, juanpablogm12 commented
se implementa funcionalidad para que cargue en el componente payments y orders

2023-03-17 18:11 UTC, sdelp66 approved these changes
Muy bien Juan Pablo!!! buen trabajo!!!

2023-03-17 18:25 UTC, merged